#!/bin/bash
#credit https://github.com/web3cdnservices/autonity-validator-toolkit/blob/main/tools/get_aut_api_key

ROOT_PATH=$( dirname -- "$( readlink -f -- "$0"; )"; );

echo $(<"$ROOT_PATH/../.data/.autonity/autonity_api.token") | jq -r ".apikey"
